language: go

go:
    - 1.0
    - 1.1
    - tip

notifications:
    irc:
        channels:
            - "irc.freenode.org#lspace"
        template:
            - "Build #%{build_number} - %{branch} - %{commit} - %{message}"
        on_success: always # default: always [always|never|change]
        on_failure: always # default: always [always|never|change]
        use_notice: true
        skip_join: true
