language: c

before_script:
    - export PREFIX=/usr
    - wget http://libsdl.org/release/SDL2-2.0.1.tar.gz -O - | tar xz
    - (cd SDL2-2.0.1 && ./configure --prefix=$PREFIX && make -j5 && make install)
    - wget http://libsdl.org/projects/SDL_image/release/SDL2_image-2.0.0.tar.gz -O - | tar xz
    - (cd SDL2_image-2.0.0 && ./configure --prefix=$PREFIX && make -j5 && make install)
    - wget http://libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.0.tar.gz -O - | tar xz
    - (cd SDL2_mixer-2.0.0 && ./configure --prefix=$PREFIX && make -j5 && make install)

script: mkdir build && cd build && cmake .. && make && make test

notifications:
    irc:
        channels:
            - "irc.freenode.org#lspace"
        template:
            - "Build #%{build_number} - %{branch} - %{commit} - %{message}"
        on_success: always # default: always [always|never|change]
        on_failure: always # default: always [always|never|change]
        use_notice: true
