language: c

before_script:
    sudo apt-get install libwebp-dev libpng-dev libjpeg-dev

script: mkdir build && cd build && cmake .. && make && make test

notifications:
    irc:
        channels:
            - "irc.freenode.org#lspace"
        template:
            - "Build #%{build_number} - %{branch} - %{commit} - %{message}"
        on_success: always # default: always [always|never|change]
        on_failure: always # default: always [always|never|change]
        use_notice: true
