flags: {}
packages:
- '.'
- location:
    git: https://github.com/nitrix/sdl2-image
    commit: 0808be3039ce362402166cfdd02fb74c6cd4a2a3
extra-deps:
- sdl2-2.1.0
- sdl2-ttf-1.0.0
- persistent-sqlite-2.2.1
- persistent-2.2.4
resolver: lts-5.6
