flags: {}
packages:
- '.'
#- location:
#    git: https://github.com/nitrix/sdl2-image
#    commit: 93744a9e4d4993ebe49e160b5efc7b072553de4a
#- location:
#    git: https://github.com/nitrix/sdl2
#    commit: c1532a34f2a5a7fcfe22c80893ee83f8bd940223
#extra-deps:
#- sdl2-ttf-1.0.0
resolver: lts-7.9 #nightly-2016-06-29
